/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  UNITY_EXEC_TIME_START(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UNITY_EXEC_TIME_STOP(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#define UNITY_INCLUDE_SETUP_STUBS
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "foo.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_foo1(void);
extern void test_foo2(void);
extern void test_sort1(void);
extern void test_sort_duplicatedValues(void);
extern void test_sort_negativeValues(void);
extern void test_sort_OneValue(void);
extern void test_sort_OneValueDifferent(void);
extern void test_sort_OnlyNegativeValues(void);
extern void test_sort_BigArray(void);
extern void test_sort_With0Values(void);
extern void test_sort_WithDifferentSizes(void);
extern void test_sort_ArrayOfChars(void);
extern void test_sort_BigAndWorstCase(void);
extern void test_sort_BigAndBestCase(void);
extern void test_sort_EmptyArray(void);
extern void test_sort_DecimalValues(void);
extern void test_sort_NullArray(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("test/TestFoo.c");
  RUN_TEST(test_foo1, 15);
  RUN_TEST(test_foo2, 22);
  RUN_TEST(test_sort1, 27);
  RUN_TEST(test_sort_duplicatedValues, 40);
  RUN_TEST(test_sort_negativeValues, 67);
  RUN_TEST(test_sort_OneValue, 80);
  RUN_TEST(test_sort_OneValueDifferent, 93);
  RUN_TEST(test_sort_OnlyNegativeValues, 106);
  RUN_TEST(test_sort_BigArray, 119);
  RUN_TEST(test_sort_With0Values, 132);
  RUN_TEST(test_sort_WithDifferentSizes, 145);
  RUN_TEST(test_sort_ArrayOfChars, 158);
  RUN_TEST(test_sort_BigAndWorstCase, 170);
  RUN_TEST(test_sort_BigAndBestCase, 182);
  RUN_TEST(test_sort_EmptyArray, 194);
  RUN_TEST(test_sort_DecimalValues, 206);
  RUN_TEST(test_sort_NullArray, 218);

  return suite_teardown(UnityEnd());
}
